#!/bin/bash

# Get the last component of the current working directory
last_component=$(basename "$PWD")

# Check if the last component is "mpapers"
if [ "$last_component" != "mpapers" ]; then
    # Create subdirectory "mpapers" if it doesn't exist
    if [ ! -d "mpapers" ]; then
        mkdir "mpapers"
    fi

    # Change directory to "mpapers"
    cd "mpapers" || exit 1
fi

wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Geometry%20of%20the%20Compactification%20of%20the%20Hurwitz%20Scheme.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Geometry%20of%20the%20Compactification%20of%20the%20Hurwitz%20Scheme%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/On%20Semi-positivity%20and%20Filtered%20Frobenius%20Crystals.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Correspondences%20on%20Hyperbolic%20Curves.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Correspondences%20on%20Hyperbolic%20Curves%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Extending%20Families%20of%20Curves%20over%20Log%20Regular%20Schemes.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Noncritical%20Belyi%20Maps.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Noncritical%20Belyi%20Maps%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Arithmetic%20Elliptic%20Curves%20in%20General%20Position.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Arithmetic%20Elliptic%20Curves%20in%20General%20Position%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Intrinsic%20Hodge%20Theory%20of%20p-adic%20Hyperbolic%20Curves%20(ICM98).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Intrinsic%20Hodge%20Theory%20of%20Hyperbolic%20Curves%20(Seoul%201998).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Intrinsic%20Hodge%20Theory%20of%20p-adic%20Hyperbolic%20Curves%20(Nara%201998).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/A%20Theory%20of%20Ordinary%20p-adic%20Curves.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/A%20Theory%20of%20Ordinary%20p-adic%20Curves%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Foundations%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/An%20Introduction%20to%20p-adic%20Teichmuller%20Theory.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/An%20Introduction%20to%20p-adic%20Teichmuller%20Theory%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Profinite%20Grothendieck%20Conjecture%20for%20Closed%20Hyperbolic%20Curves%20over%20Number%20Fields.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Profinite%20Grothendieck%20Conjecture%20for%20Closed%20Hyperbolic%20Curves%20over%20Number%20Fields%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/A%20Version%20of%20the%20Grothendieck%20Conjecture%20for%20p-adic%20Local%20Fields.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Local%20Pro-p%20Anabelian%20Geometry%20of%20Curves.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Local%20Pro-p%20Anabelian%20Geometry%20of%20Curves%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Grothendieck%20Conjecture%20on%20the%20Fundamental%20Groups%20of%20Algebraic%20Curves.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Absolute%20Anabelian%20Geometry.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Absolute%20Anabelian%20Geometry%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Canonical%20Liftings.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Canonical%20Liftings%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Topics%20Surrounding%20the%20Anabelian%20Geometry%20of%20Hyperbolic%20Curves.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Geometry%20of%20Anabelioids.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Geometry%20of%20Anabelioids%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Categorical%20Representation%20of%20Locally%20Noetherian%20Log%20Schemes.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Categorical%20Representation%20of%20Locally%20Noetherian%20Log%20Schemes%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Categories%20of%20Log%20Schemes%20with%20Archimedean%20Structures.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Categories%20of%20Log%20Schemes%20with%20Archimedean%20Structures%20(LaTeX%20version).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Categories%20of%20Log%20Schemes%20with%20Archimedean%20Structures%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Semi-graphs%20of%20Anabelioids.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Semi-graphs%20of%20Anabelioids%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Galois%20Sections.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Galois%20Sections%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Combinatorial%20Grothendieck%20Conjecture.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Combinatorial%20Grothendieck%20Conjecture%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Categories%20of%20Hyperbolic%20Riemann%20Surfaces.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Categories%20of%20Hyperbolic%20Riemann%20Surfaces%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Absolute%20Anabelian%20Cuspidalizations.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Absolute%20Anabelian%20Cuspidalizations%20(LaTeX%20version).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Absolute%20Anabelian%20Cuspidalizations%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Geometry%20of%20Frobenioids%20I.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Geometry%20of%20Frobenioids%20I%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Geometry%20of%20Frobenioids%20II.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Geometry%20of%20Frobenioids%20II%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Global%20Solvably%20Closed%20Anabelian%20Geometry.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Global%20Solvably%20Closed%20Anabelian%20Geometry%20(LaTeX%20version).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Etale%20Theta%20Function%20and%20its%20Frobenioid-theoretic%20Manifestations.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Etale%20Theta%20Function%20and%20its%20Frobenioid-theoretic%20Manifestations%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Etale%20Theta%20Function%20and%20its%20Frobenioid-theoretic%20Manifestations%20(related%20expositions).pdf"
wget "http://www.kurims.kyoto-u.ac.jp/~motizuki/Responses%20to%20questions%20on%20Frobenioids.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Algebraic%20and%20Anabelian%20Geometry%20of%20Configuration%20Spaces.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Algebraic%20and%20Anabelian%20Geometry%20of%20Configuration%20Spaces%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Algebraic%20and%20Anabelian%20Geometry%20of%20Configuration%20Spaces%20(comments%20on%20strongly%20torsion-free%20groups).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Topics%20in%20Absolute%20Anabelian%20Geometry%20I.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Topics%20in%20Absolute%20Anabelian%20Geometry%20I%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Topics%20in%20Absolute%20Anabelian%20Geometry%20II.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Topics%20in%20Absolute%20Anabelian%20Geometry%20II%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Topics%20in%20Absolute%20Anabelian%20Geometry%20III.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Topics%20in%20Absolute%20Anabelian%20Geometry%20III%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Combinatorial%20Cuspidalization.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Combinatorial%20Cuspidalization%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Nodally%20Nondegenerate%20Outer%20Representations.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Nodally%20Nondegenerate%20Outer%20Representations%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Combinatorial%20Anabelian%20Topics%20I.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Combinatorial%20Anabelian%20Topics%20I%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Combinatorial%20Anabelian%20Topics%20II.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Combinatorial%20Anabelian%20Topics%20III.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Combinatorial%20Anabelian%20Topics%20IV.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Monomorphisms%20in%20Categories%20of%20Log%20Schemes.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Numerical%20invariants%20and%20distinguished%20subgroups%20of%20configuration%20spaces.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Combinatorial%20absolute%20Galois%20groups.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Resolution%20of%20Nonsingularities%20for%20Arbitrary%20Hyperbolic%20Curves.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Hodge-Arakelov%20Theory%20of%20Elliptic%20Curves.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Scheme-theoretic%20Theta%20Convolution.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Galois-Theoretic%20Kodaira-Spencer%20Morphism%20of%20an%20Elliptic%20Curve.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/The%20Hodge-Arakelov%20Theory%20of%20Elliptic%20Curves%20in%20Positive%20Characteristic.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/A%20Survey%20of%20the%20Hodge-Arakelov%20Theory%20of%20Elliptic%20Curves%20I.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/A%20Survey%20of%20the%20Hodge-Arakelov%20Theory%20of%20Elliptic%20Curves%20I%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/A%20Survey%20of%20the%20Hodge-Arakelov%20Theory%20of%20Elliptic%20Curves%20II.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/A%20Survey%20of%20the%20Hodge-Arakelov%20Theory%20of%20Elliptic%20Curves%20II%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Anabelian%20Geometry%20in%20the%20Hodge-Arakelov%20Theory%20of%20Elliptic%20Curves%20(Kokyuroku%202002).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Inter-universal%20Teichmuller%20Theory%20I.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Inter-universal%20Teichmuller%20Theory%20II.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Inter-universal%20Teichmuller%20Theory%20III.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Inter-universal%20Teichmuller%20Theory%20IV.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Panoramic%20Overview%20of%20Inter-universal%20Teichmuller%20Theory.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Panoramic%20Overview%20of%20Inter-universal%20Teichmuller%20Theory%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Bogomolov%20from%20the%20Point%20of%20View%20of%20Inter-universal%20Teichmuller%20Theory.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Bogomolov%20from%20the%20Point%20of%20View%20of%20Inter-universal%20Teichmuller%20Theory%20(comments).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Alien%20Copies,%20Gaussians,%20and%20Inter-universal%20Teichmuller%20Theory.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Explicit%20estimates%20in%20IUTeich.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/Essential%20Logical%20Structure%20of%20Inter-universal%20Teichmuller%20Theory.pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/IUT%20as%20an%20Anabelian%20Gateway%20(MFO-RIMS23%20Oberwolfach%20Report).pdf"
wget "https://www.kurims.kyoto-u.ac.jp/~motizuki/list-of-papers.pdf"